name: Generate Tetris Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read
  issues: read

jobs:
  build:
    name: Generate 3D Contribution Graph
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate 3D Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: vinisant0lopes-crypto

      - name: Commit files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "generated 3D graph"
          git push
